CUDA_VISIBLE_DEVICES=2,3,4,5 python tracking/test.py   ceutrack ceutrack_coesot_30 --dataset coesot --threads 8 --num_gpus 4
CUDA_VISIBLE_DEVICES=2,3,4,5 python tracking/test.py   ceutrack ceutrack_coesot_35 --dataset coesot --threads 8 --num_gpus 4
CUDA_VISIBLE_DEVICES=2,3,4,5 python tracking/test.py   ceutrack ceutrack_coesot_40 --dataset coesot --threads 8 --num_gpus 4
CUDA_VISIBLE_DEVICES=2,3,4,5 python tracking/test.py   ceutrack ceutrack_coesot_45 --dataset coesot --threads 8 --num_gpus 4
CUDA_VISIBLE_DEVICES=2,3,4,5 python tracking/test.py   ceutrack ceutrack_coesot_50 --dataset coesot --threads 8 --num_gpus 4
# CUDA_VISIBLE_DEVICES=2,3 python tracking/test.py   ceutrack ceutrack_fe108_25 --dataset fe108 --threads 6 --num_gpus 2
# CUDA_VISIBLE_DEVICES=2,3 python tracking/test.py   ceutrack ceutrack_fe108_30 --dataset fe108 --threads 6 --num_gpus 2
# CUDA_VISIBLE_DEVICES=2,3 python tracking/test.py   ceutrack ceutrack_fe108_40 --dataset fe108 --threads 6 --num_gpus 2
# CUDA_VISIBLE_DEVICES=2,3 python tracking/test.py   ceutrack ceutrack_fe108_50 --dataset fe108 --threads 6 --num_gpus 2